name:                iohk
version:             0.1.0.0
github:              "Nickske666/iohk"
license:             BSD3
author:              "Nick Van den Broeck"
maintainer:          "nick.van.den.broeck666@gmail.com"
copyright:           "2018 Nick Van den Broeck"

extra-source-files:
- README.md
- ChangeLog.md

description:         See README at https://github.com/Nickske666/iohk

dependencies:
- base >= 4.7 && < 5
- distributed-process >= 0.7 && < 0.8
- random >= 1.1 && < 1.2
- network-transport-tcp >= 0.5 && < 0.6
- binary >= 0.8 && < 0.9
- mtl >= 2.2 && < 2.3

library:
  source-dirs: src

executables:
  iohk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iohk

tests:
  iohk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iohk
